OPTS = -DRESAMPLE -DVISEXPORT -DDSD -DIR -DGPIO -DRPI -DUSE_SSL -DNO_SSLSYM -I./include -I./include/opus -I./include/alac -I/usr/local/include -s -march=armv6 -mfloat-abi=hard -mfpu=vfp

LDFLAGS=-L./lib -L/usr/local/lib -s -lgomp

include Makefile

# https://docs.picoreplayer.org/components/squeezelite/
# Build options: LINUX ALSA EVENTFD RESAMPLE FFMPEG OPUS VISEXPORT IR GPIO RPI DSD SSL NO_SSLSYM
